### PR TITLE
Improve SRC, HRC parsing

### PR DESCRIPTION
**Pull request by lukedrum**
Add ability to use translator without SRC, HRC fields in XLS data file

### CODE REVIEW

**Comment by Qub3k** [comment]
@lukedrum I cannot merge your code since `src_exist` and `hrc_exist` are not defined anywhere.

**Comment by lukedrum** [comment]
@Qub3k I added missing code as well as "tidy" part.

**Comment by Qub3k** [comment]
@lukedrum, what is the purpose of the ["additional_data" field](https://github.com/LucjanJanowski/translator-to-suJSON/blob/improve_SRC_HRC_parsing/data/config_tidy.json#L39)?

If this deals with some internal design goals of the AGH/NTIA 14-505 subjective test, I think we should leave this out.

**Comment by slhck** [comment]
Ah, I see now that this branch has a few conflicts with mine. I thought everything was merged (hence my question if I could go ahead with changes after QoMEX).

I suggest merging this onto the branch in #11 by simply importing the `functions` stuff and exchanging the `import_xslx`/`import_csv` code for what is in here. Only the file path handling has to be removed since I took care of that via the `input_file`/`output_file` arguments.

**Comment by Qub3k** [comment]
Yeah, I think merging it with #11 is the best idea. Luckily, It should be relatively straight forward.

**Comment by lukedrum** [comment]
All my work is copied to #12 . This pull request can be closed

> @lukedrum, what is the purpose of the "additional_data" field?
> If this deals with some internal design goals of the AGH/NTIA 14-505 subjective test, I think we should leave this out.
It is a scratch for future use (e.g. additional subject information)

**Pull request closed without merging**
