### PR TITLE
Tidy and non tidy dataset package

### PR DESCRIPTION
**Pull request by lukedrum**
Tidy and non-tidy file support, config file "tidy" modification, tidy dataset AGH_NTIA_14-505

### CODE REVIEW

**Comment by slhck** [comment]
Looks good to me!

**Comment by lukedrum** [comment]
I checked it using three datasets. Seems like it works.

**Comment by slhck** [comment]
@Qub3k Should I merge this or do you want to still change something? Once it is merged, the structure is in place to do some more changes on top of it.

**Comment by Qub3k** [comment]
I am sorry for the long delay in responding to this. If you both say the changes are good I am ok with merging this one.

**Comment by slhck** [comment]
Yes, please do :)

**Comment by Qub3k** [comment]
One more thing, we do not yet have any heuristic of detecting whether a given XLS file is tidy, right?

**Comment by slhck** [comment]
Thanks for merging!

No we don't. I think we'd need to simplify a few more things in the config and assume very simple input files (see the Google Doc with the spec).

I can have a look in the coming week to see what can be done there.

**Pull request merged**
